name: Update README with GitHub Account Info

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Grant permission to write to the repository contents
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Insert GitHub Account Info into README
        uses: kotorkovsciy/github-account-info-2-readme@v0.0.1
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Repository token
          username: vicimpa
          readme: README.md
