name: Update README with the latest repository

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # Run every hour

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Permission to write to the repository content

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Insert GitHub Account Info into README
        uses: kotorkovsciy/github-account-info-to-readme@v0.0.1
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Repository token
          username: vicimpa
          readme: README.md
